### ISSUE TITLE
pdf for  "Meta-Graph Based Recommendation Fusion over Heterogeneous Information Networks"

### ISSUE THREAD

**Issue by Sandy4321** [HKUST-KnowComp/FMG#12]
there is no such a paper in
http://web.cs.ucla.edu/~yzsun/Publications.htm

The code KDD17 paper "Meta-Graph Based Recommendation Fusion over Heterogeneous Information Networks"

**Comment by hzhaoaf** [comment]
@Sandy4321 check our paper: http://www.cse.ust.hk/~hzhaoaf/data/kdd17-paper.pdf
