### ISSUE TITLE
I'm confused about the dir "matlab" and i wonder how to use the dataset CIKM-YELP

### ISSUE THREAD

**Issue by ytc272098215** [HKUST-KnowComp/FMG#14]
May i ask what function is the code in "matlab"? I have noticed that the dataset CIKM-YELP and CIKM-Douban is a *.mat file. So i guess these codes are for these 2 datasets, am i right
then i wonder how to use the code on yelp.mat. it seems that the input format is not matched.

**Comment by ytc272098215** [comment]
I have seen the metapaths used in SemRec CIKM-YELP. His metapaths are all like U-*-U, ie from U to U, while I think your model need metapaths like U-*-B, ie from U to B. So how did you deal with that? Add a B to the tail of theirs or other way?

**Comment by ytc272098215** [comment]
Well， I got the metapaths in the file "fm_with_glasso". Im sory for my stupid question. But im still confused about the function of the code in "matlab". Could you expain it a little for me? Thanks a lot~~~

**Comment by hzhaoaf** [comment]
@ytc272098215 In fact, you can ignore the code in matlab, which is not relevant to KDD paper.
