### ISSUE TITLE
I'd like to ask something about computer configuration.

### ISSUE THREAD

**Issue by BIurryface** [HKUST-KnowComp/FMG#15]
When I apply this project on my computer, the python ended up with Memoryerror. 
So I want to know in order to finish this project, how much memory do I need?
Waiting for reply, thank you.

**Comment by hzhaoaf** [comment]
@BIurryface The programs can work in my Linux server with 32GB memory.

**Comment by Sandy4321** [comment]
can it work on Windows computer and Python 3?

**Comment by hzhaoaf** [comment]
@Sandy4321 Check  #16
