### ISSUE TITLE
can it work on Windows computer?

### ISSUE THREAD

**Issue by Sandy4321** [HKUST-KnowComp/FMG#16]
can it work on Windows computer?
and what RAM size needed?

**Comment by hzhaoaf** [comment]
@Sandy4321 I think it can work on Windows, though I didn't test it on Windows. In my Linux server, the RAM is 32GB.

For python 3, I am afraid it cannot. I use python 2.7 to implement all this modules.

**Comment by Iamcsy** [comment]
how to make it work on Windows computer? Thank you very much

**Comment by hyx321** [comment]
@Iamcsy I think you should work it on Linux . If working on Windows , you 'll get some problems.It's too terrible!

**Comment by Iamcsy** [comment]
ok,thank you
