### ISSUE TITLE
What meas about this dataset

### ISSUE THREAD

**Issue by 1027402982** [HKUST-KnowComp/FMG#17]
Sorry to disturb you sir ,but I do not know what means about this dataset such as aids.txt , bid_cat.txt , bid_city.txt from yelp-50k\exp_split\1, What does each row's argument mean. In other way ,  from sim_res\path_count , su as UNBUB_top500.res , what does each row's argument mean , and the parameter for third column is not represent rating, right?

**Comment by hzhaoaf** [comment]
@1027402982 
The third column in UNBUN_top500.res (or other files in the same dir) records the frequency of the meta-graph connecting the user (first column) and item (second column), i.e., representing the similarity under that meta-graph.
