### ISSUE TITLE
No module named yaml

### ISSUE THREAD

**Issue by YutingSun163** [HKUST-KnowComp/FMG#24]
Hello~ When I run the following command "python run_exp.py config/yelp-50k.yaml", an error occurred:
Traceback (most recent call last):
  File "run_exp.py", line 11, in <module>
    import yaml
ImportError: No module named yaml

do you have any idea why this would happen? 
My python version is 2.7.10, and OS is macOs 10.14.2. And I did fine on previous steps.

**Comment by hzhaoaf** [comment]
@YutingSun163 You need to install the corresponding module, [pyyaml](https://pyyaml.org/), which parses the config file in yaml format. 

The version in my server is pyyaml 3.1, which is default installed in Anaconda. You may install it in your macbook.
