### ISSUE TITLE
The original data of amazon-200K

### ISSUE THREAD

**Issue by minksable** [HKUST-KnowComp/FMG#25]
Hi, the dataset of amazon-200k is preprocessed and only has id numbers. Is it possible to provide the original metadata of products (i.e., the metadata of each row in bid.txt)? Thanks very much.

**Comment by hzhaoaf** [comment]
@minksable Hi, sorry that I cannot provide the original metadata of products, since this dataset is randomly sampled from the original dataset and the ids have been converted for easy use. The id maps are not saved.

**Comment by minksable** [comment]
I got it. Thanks anyway :)
