### ISSUE TITLE
An issue about datasets

### ISSUE THREAD

**Issue by rogerhome11** [HKUST-KnowComp/FMG#26]
Merry Christmas Dr. zhao, sorry to disturb you.  I have unzipped  the amazon/yelp datasets and  found the uid_rid_pos_aid_weight.txt in them.  Are them  the origin files in each datasets?  If not , how did you calculate the weight for each user in each datasets?

**Comment by hzhaoaf** [comment]
@rogerhome11 Thanks for your interests in our work.

The weight in the file "uid_rid_pos_aid_weight.txt" represents the probability of the aspect belonging to this review. And the probability is generated by topic model (LDA), which is trained by all the reviews. We have give a brief instruction in the paper (Sec 4.4)

![image](https://user-images.githubusercontent.com/1212489/71448568-81797180-2778-11ea-82db-31037af53ab6.png)
