### ISSUE TITLE
关于mf_features的疑惑

### ISSUE THREAD

**Issue by xuelun** [HKUST-KnowComp/FMG#3]
在网上看的您的文章https://mp.weixin.qq.com/s/6XMJJQQKolv1AS3em1ICZg，感觉很不错，下载代码进行阅读。

请问mf_features/path_count下面的文件是从何而来的，这个貌似跟meta_graph有关，而您的代码中居然是直接用这些文件的，那么自己想本地跑一份应该如何做呢？谢谢

关于代码质量需要改善的地方貌似不少
（1）data文件夹放到指定路径
（2）mkdir log
（3）mkdir fm_res
（4）run_exp.py文件中run_regsvd函数中fm_ak_gl = MF(config, data_loader)这一句，MF未定义

**Comment by hzhaoaf** [comment]
@xuelun 感谢你对我们工作的兴趣，同时提出了非常好的问题和建议。

首先代码里提到的几个问题（4），是我在整理代码时的一个疏忽，这个方法实际是运行标准矩阵分解的实验，直接调用mf.py文件里的MF_BGD即可。因为和我们的方法不相关，已经将这个方法删除。

问题（1）已经写在readme里。（2）和（3）因为本地gitignore导致目录没有提交到github，已经更新到readme文件。

至于mf_features/path_count这个文件是我们用meta-graph生成相似度矩阵后分解得到的隐式特征，这部分代码由于非常涉及到的业务逻辑比较复杂，代码有很多针对数据的硬编码，即使发布出来也非常难用。如果只是想复现我们的实验，直接运行run_exp.py里的方法即可。如果想重新生成meta-graph based latent features，可能需要自己生成代码，思路和我们论文里写到的一样，先计算number of meta-graph connect user and item, 然后对相似度矩阵进行分解即可。
