### ISSUE TITLE
How to process the original data into similarity matrix?

### ISSUE THREAD

**Issue by liangqq6** [HKUST-KnowComp/FMG#4]
May I ask how to process the original data into similarity matrix? It seems that the file "mf_features_generator.py" is used to conduct matrix factorization from each similarity matrix corresponding to each meta graph. But how to get the similarity first? That is, how to implement section 2.1 in the paper? 
Looking forward to your reply, thanks!

**Comment by hzhaoaf** [comment]
@liangqq6 Sorry for the late reply. I updated the code to compute the meta-graph based similarity matrices. You may check the latest ReadMe file.
