### ISSUE TITLE
Can't open the website of readme.md

### ISSUE THREAD

**Issue by hyx321** [HKUST-KnowComp/FMG#5]
this week ,I get nothing when I open the website of readme several times.md.It shows nothing .

**Comment by hzhaoaf** [comment]
@hyx321 
Thanks for your interests in our work.

What do you mean by nothing? Can you give more information about it, like screenshots? That will be very helpful.

**Comment by hyx321** [comment]
After I run  the code :"python 200k_commu_mat_computation.py yelp-50k all 1",I got a error.And I also 
conda install bottleneck.I use windows OS.
![image](https://user-images.githubusercontent.com/36033268/37963510-0c1233ba-31f1-11e8-8a29-c8ddfa631a93.png)

**Comment by hzhaoaf** [comment]
@hyx321 

What's your version of bottleneck? Mine is 
`bottleneck.__version__`
`Out[3]:` '1.1.0'

Seems the method argpartsort is not available in your bottleneck.

**Comment by hyx321** [comment]
today ,follow your advice,I changed the version.And the error was gone.but I get another error.By the way,I revised the code that is "f = open(ind2rid_filename, 'rb')",this code is at 265lines in 200k_commu_mat_computation.py .Tomrrow ,I'lltry to run this Project in Linux.
![image](https://user-images.githubusercontent.com/36033268/38036565-8dcc8cc8-32d9-11e8-8bb6-6cfd626c8104.png)

**Comment by hyx321** [comment]
today,I build a virtual machine of Ubuntu.After run this project ,the last error about"cpickle.UnpicklineError" has gone and I get a sad error about Memory,I give it about 6.5G Memory.When it run ,My windows only have 1G  for free .and I have 12G in total .
![q_vtsm5d iae hnp4_ 58gs](https://user-images.githubusercontent.com/36033268/38086964-f3f8520c-3388-11e8-9e26-42d95bd463f2.png)

**Comment by hzhaoaf** [comment]
@hyx321 
I test the whole program again, I think you need around 16G Memory in Linux server.

**Comment by hyx321** [comment]
Thank you for your helping these days.After receiving your e-mail , I try to decrease datas properly in every txt ,and I get a error " **Keyerror :640698**".So ,do you have a smaller data to let me run this program?please.

**Comment by hzhaoaf** [comment]
@hyx321 
If what you need is to execute the whole process, you may comment the Line 458-460, which caused the memory problem. It computed two meta-graph based similarity matrices, however, you can execute the whole process without them. The needed latent features are already in the directory "yelp-50k/exp_split/1/mf_features/path_count".

**Comment by hyx321** [comment]
Thank you for you advice ,I run this program successful,and it only need 6.1G.Honestly,It is a good news for me. Parsing code is my next step .
