### ISSUE TITLE
The dataset is unavailable?

### ISSUE THREAD

**Issue by yiranxijie** [HKUST-KnowComp/FMG#6]
Sorry, The link (which is [https://www.dropbox.com/s/io915s8mdwph46e/data.zip?dl=0](url) ) you have provided is unavailable?
![image](https://user-images.githubusercontent.com/12460007/37817546-0bbd3816-2eb2-11e8-8483-346ba31ac2b5.png)

**Comment by hzhaoaf** [comment]
@yiranxijie 
Thanks for pointing this out. It's caused by an unexpected operation in my Dropbox.

I added the yelp-50k and amazon-50k datasets to the project directory, you may pull the latest update and check the "FMG_released_data.zip".

**Comment by yiranxijie** [comment]
Ok, I got it, thanks a lot!
