### ISSUE TITLE
Input parameters of mf.py

### ISSUE THREAD

**Issue by SeverusBing** [HKUST-KnowComp/FMG#8]
Hi Dr. Zhao, I performed the latest code recently and I finally stopped by an input error in the file 'mf.py'.

There is a class 'MF_BGD' in 'mf.py' and the attribute '_init_' of it needs a parameter 'data', when this input parameter is 'None', the function will read a data file called **'data/ml-1m-rating.txt**'. I found that there was no such file in your data package so I wonder if you mind showing an format example of the file here, cause I don't know which form to transform my data in or what kind of data I should use.

Also, I will be very appreciated if you can tell the details about all parameters of 'MF_BGD', such as 'train_data' and 'test_data'.

Thank you for your kindly help! I am looking forward to your reply.

**Comment by hzhaoaf** [comment]
@SeverusBing Which part are you running when you encounter this error?

In fact, **the parameter "data" in the init functions is the union set of training data and test data**. You may check Line 234 in method "run_baseline", which show you how to give the input parameters.

For train_data and test_data, their format are triplets, i.e., (user_id, item_id, rating). You can check the data in "**_data/yelp-50k/exp_split/1/ratings_train_1.txt_**" when you unzip the **_FMG_released_data.zip_** in this project.

The case when "data=None" is an early-stage code for me to test other datasets. You can just ignore it actually.

**Comment by SeverusBing** [comment]
Oh, I see!

So I just need delete the "None" choice for parameter "data" to run the function?

I will try again immediately, thanks for your patient explain!
