### ISSUE TITLE
What does "neg" and "pos" mean in the dataset?

### ISSUE THREAD

**Issue by leetiantian** [HKUST-KnowComp/FMG#9]
Hi Dr. Zhao, I've downloaded the datasets and run the code successfully. But I'm quite confused about what the "neg" and "pos" mean in the files "uid_neg_bid.txt" and "uid_pos_bid.txt" and also in files "uid_rid_neg_aid.txt" and "uid_rid_neg_aid_weight.txt". I guess the "neg" means lower ratings and "pos" means higher ratings. But after comparing these files with ratings.txt, I found uid_neg_bid.txt contains ratings from 1 to 4 and uid_pos_bid.txt contains ratings from 1 to 5. It seems that my assumption is wrong.
Could you kindly explain what "pos" and "neg" mean in these files?  Thank you for your help! Looking forward to your reply.

**Comment by hzhaoaf** [comment]
@leetiantian 
You may check my reply to [Issue 10](issues about rating value #10 )
